# Generated by Django 3.0.8 on 2021-03-10 04:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantrequest',
            name='ip',
            field=models.GenericIPAddressField(default="192.168.134.1"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchantrequest',
            name='returnUrl',
            field=models.URLField(default="https://www.google.com"),
            preserve_default=False,
        ),
    ]
