# Generated by Django 3.0.8 on 2021-03-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210310_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantrequest',
            name='isProcessed',
            field=models.BooleanField(default=False),
        ),
    ]
