# Generated by Django 3.0.8 on 2021-04-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_shadepayrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='shadepayrequest',
            name='products',
            field=models.CharField(default='Bags', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shadepayrequest',
            name='products_description',
            field=models.CharField(default='Sample bag', max_length=255),
            preserve_default=False,
        ),
    ]
