# Generated by Django 3.0.8 on 2021-04-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210409_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='shadepayrequest',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
