# Generated by Django 3.0.8 on 2020-12-14 23:38

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(blank=True, max_length=255)),
                ('bank_code', models.IntegerField()),
                ('dob', models.DateField()),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True)),
                ('link', models.CharField(max_length=255)),
                ('balance', models.DecimalField(decimal_places=3, max_digits=255)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(max_length=255)),
                ('card_num', models.IntegerField()),
                ('card_cvv', models.IntegerField()),
                ('card_exp_date', models.DateField()),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IndividualWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True)),
                ('link', models.CharField(max_length=255)),
                ('balance', models.DecimalField(decimal_places=3, max_digits=255)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavingWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True)),
                ('link', models.CharField(max_length=255)),
                ('balance', models.DecimalField(decimal_places=3, max_digits=255)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_due', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_code', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=3, max_digits=255)),
                ('currency', models.CharField(max_length=255)),
                ('status_code', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now=True)),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever_transactions', to=settings.AUTH_USER_MODEL)),
                ('reciever_bank', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_bank', to='main.Bank')),
                ('reciever_business_wallet', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_business_wallet', to='main.BusinessWallet')),
                ('reciever_individual_wallet', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_individual_wallet', to='main.IndividualWallet')),
                ('reciever_saving_wallet', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_saving_wallet', to='main.SavingWallet')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_transactions', to=settings.AUTH_USER_MODEL)),
                ('sender_bank', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_bank', to='main.Bank')),
                ('sender_business_wallet', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_business_wallet', to='main.BusinessWallet')),
                ('sender_card', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_card', to='main.Card')),
                ('sender_individual_wallet', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_individual_wallet', to='main.IndividualWallet')),
                ('sender_saving_wallet', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_saving_wallet', to='main.SavingWallet')),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('login_location', models.CharField(max_length=255)),
                ('login_device', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=255, unique=True)),
                ('date_registered', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer_details', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer_wallet_details', to='main.BusinessWallet')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BVN', models.IntegerField(unique=True)),
                ('DOB', models.CharField(blank=True, max_length=255)),
                ('mobile', models.CharField(blank=True, max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('billing_address', models.CharField(max_length=255)),
                ('shipping_address', models.CharField(max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(default='Nigeria', max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
