# Generated by Django 3.0.8 on 2021-02-16 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210109_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesswallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=255),
        ),
        migrations.AlterField(
            model_name='individualwallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=255),
        ),
        migrations.AlterField(
            model_name='savingwallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=255),
        ),
        migrations.CreateModel(
            name='ProcessCardRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=255)),
                ('card_first_six', models.CharField(max_length=255)),
                ('card_last_four', models.CharField(max_length=255)),
                ('card_type', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now=True)),
                ('business_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topup_request_business_walet', to='main.BusinessWallet')),
                ('individual_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topup_request_individual_walet', to='main.IndividualWallet')),
                ('saving_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topup_request_saving_walet', to='main.SavingWallet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topup_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
