# Generated by Django 3.0.8 on 2021-03-01 08:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210227_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='user',
        ),
        migrations.AddField(
            model_name='businesswallet',
            name='api_key',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesswallet',
            name='secrete_key',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='additionalinformation',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
