# Generated by Django 3.0.8 on 2021-03-01 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210301_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesswallet',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='businesswallet',
            name='secrete_key',
        ),
        migrations.AddField(
            model_name='developer',
            name='secrete_key',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
