# Generated by Django 3.0.8 on 2021-03-01 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210301_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_address', models.CharField(max_length=255)),
                ('business_phone', models.CharField(max_length=255)),
                ('business_email', models.CharField(max_length=255)),
                ('business_nature', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer_details', to='main.Developer')),
            ],
        ),
    ]
