# Generated by Django 3.0.8 on 2021-03-03 05:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_processpayattituderequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='processcardrequest',
            name='transaction_code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processpayattituderequest',
            name='transaction_code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
