# Generated by Django 3.0.8 on 2021-03-03 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210303_0533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processcardrequest',
            name='transaction_code',
        ),
        migrations.RemoveField(
            model_name='processpayattituderequest',
            name='transaction_code',
        ),
    ]
