# Generated by Django 3.0.8 on 2021-03-03 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210303_0536'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedUnprocessedCardRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unprocessed_transaction', to='main.ProcessCardRequest')),
            ],
        ),
    ]
