# Generated by Django 3.0.8 on 2021-03-03 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_approvedunprocessedcardrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='mobile',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MissingWalletTransactionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_wallet_card_process', to='main.ProcessCardRequest')),
            ],
        ),
    ]
