# Generated by Django 3.0.8 on 2021-03-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210303_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reference',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
