# Generated by Django 3.0.8 on 2021-03-03 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_transaction_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingWalletCardlessTransactionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_wallet_cardless_process', to='main.ProcessPayattitudeRequest')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovedUnprocessedCardlessRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unprocessed_cardless_transaction', to='main.ProcessPayattitudeRequest')),
            ],
        ),
    ]
