# Generated by Django 3.0.8 on 2021-03-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_approvedunprocessedcardlessrequest_missingwalletcardlesstransactionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
