# Generated by Django 3.0.8 on 2021-03-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_newsletterregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingwallet',
            name='date_due',
            field=models.DateField(auto_now=True),
        ),
    ]
