# Generated by Django 3.0.8 on 2021-03-09 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('main', '0019_auto_20210307_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='processcardrequest',
            name='merchant_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_card_request', to='api.MerchantRequest'),
        ),
    ]
