# Generated by Django 3.0.8 on 2021-03-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_processcardrequest_merchant_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
