# Generated by Django 3.0.8 on 2021-03-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_logs_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='lat',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logs',
            name='lon',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logs',
            name='ip_address',
            field=models.CharField(max_length=255),
        ),
    ]
