# Generated by Django 3.0.8 on 2021-03-16 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210316_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('checkout_location', models.CharField(max_length=255)),
                ('lon', models.CharField(max_length=255)),
                ('lat', models.CharField(max_length=255)),
                ('client_device', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_logs', to='main.BusinessWallet')),
            ],
        ),
    ]
