# Generated by Django 3.0.8 on 2021-03-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_checkoutlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cost_of_transaction',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='rate_of_cost_of_transaction',
            field=models.CharField(default='1.25%', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='rate_of_transaction_charges',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_charges',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=255),
            preserve_default=False,
        ),
    ]
