# Generated by Django 3.0.8 on 2021-03-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20210317_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingwallet',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
