# Generated by Django 3.0.8 on 2021-03-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_savingwallet_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='processcardrequest',
            name='raw_data',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processpayattituderequest',
            name='raw_data',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
