# Generated by Django 3.0.8 on 2021-03-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20210319_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255)),
                ('reciever', models.CharField(max_length=255)),
                ('trx_id', models.CharField(max_length=255)),
                ('trx_date', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=255)),
                ('charges', models.DecimalField(decimal_places=2, max_digits=255)),
                ('reciever_wallet', models.CharField(max_length=255)),
                ('reciever_amount', models.DecimalField(decimal_places=2, max_digits=255)),
                ('status', models.CharField(max_length=255)),
                ('email_fro', models.CharField(max_length=255)),
                ('channel', models.CharField(max_length=255)),
                ('card', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('trx_ref', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
