# Generated by Django 3.0.8 on 2021-03-23 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_recipt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipt',
            old_name='email_fro',
            new_name='email_for',
        ),
    ]
