# Generated by Django 3.0.8 on 2021-04-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20210323_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='rate_of_transaction_charges',
            field=models.CharField(default='1.25% + 20 : Max 3500', max_length=255),
        ),
    ]
