# Generated by Django 3.0.8 on 2021-04-07 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20210407_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalinformation',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='additionalinformation',
            name='nin',
        ),
    ]
