# Generated by Django 3.0.8 on 2021-04-08 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20210407_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingwallet',
            name='user',
        ),
        migrations.RemoveField(
            model_name='processcardrequest',
            name='individual_wallet',
        ),
        migrations.RemoveField(
            model_name='processcardrequest',
            name='saving_wallet',
        ),
        migrations.RemoveField(
            model_name='processpayattituderequest',
            name='individual_wallet',
        ),
        migrations.RemoveField(
            model_name='processpayattituderequest',
            name='saving_wallet',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='reciever_individual_wallet',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='reciever_saving_wallet',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sender_individual_wallet',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sender_saving_wallet',
        ),
        migrations.DeleteModel(
            name='IndividualWallet',
        ),
        migrations.DeleteModel(
            name='SavingWallet',
        ),
    ]
