# Generated by Django 3.0.8 on 2021-04-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20210408_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalinformation',
            name='is_business',
            field=models.BooleanField(default=False),
        ),
    ]
