# Generated by Django 3.0.8 on 2021-04-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_additionalinformation_is_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesswallet',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
