# Generated by Django 3.0.8 on 2021-04-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20210412_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesswallet',
            name='address',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
